bahrain-uob/gen-ai-moe-challenge

- packages/frontend/src/App.tsx
- packages/frontend/src/sst-env.d.ts
Added Sayed Ahmed was here to App.tsx
> Adding my name to index

- packages/frontend/src/App.tsx
> added my name farha

- docs/diagrams/UI/UI using Figma
Adding Figma link to docs/diagrams
> Create UI using Figma

- packages/frontend/src/App.tsx
- packages/frontend/src/main.tsx
Add link to home page to redirect to writing page
> Link to writing page

- packages/frontend/src/pages/speaking.tsx
- packages/functions/src/speakingRecording.ts
- stacks/ApiStack.ts
- stacks/DBStack.ts
Implementing Polly for text to speech
Note: I am assuming that the key stored in DynamoDB for the Polly recording will be stored when the questions are generated. Furthermore, to test this you need to copy the objects in the `speaking-questions-polly` bucket to the `speakingpollybucket` in your stage.
> 90 speaking  using polly for text to speech

- packages/frontend/src/pages/FeedbackPage.tsx
@DanaK270 I forgot to push this change.
> Fix api call in `FeedbackPage.tsx`

- packages/frontend/src/pages/sections.tsx
just added a link to the reading page
> added a link to the reading exam page

- docs/02-deployment-architecture.md
I have added a link to draw.io
> adding link to draw.io (google drive link)

- packages/frontend/src/App.tsx
- packages/frontend/src/Layout.tsx
- packages/frontend/src/main.tsx
- packages/frontend/src/pages/ErrorPage.tsx
This will handle the errors covered by [route errors](https://reactrouter.com/en/main/utils/is-route-error-response).
> Add error page

- packages/frontend/src/pages/ReadingQuestionsPage.tsx
The split screen design is now mature.  I'm using horizontal split for larger devices and vertical split for smaller ones.
As far as I can tell it works well.  With the option of maximizing the passage screen in smaller devices.
I've settled on doing the part switching with button in the bar.
I'm not satisfied yet with the bar situation; some stuff are still left out:
- Title of 'Reading Test' (or listening).
- Back button
- Help button
But for now, what we have will do.
Will probably revise the bar when I implement #149. Same with help button for #186.
> Reading page design

- packages/frontend/src/AuthContext.tsx
- packages/frontend/src/Layout.tsx
- packages/frontend/src/main.tsx
- packages/frontend/src/pages/TestPage.tsx
- packages/frontend/src/pages/sections.tsx
- packages/frontend/src/pages/signIn.tsx
- packages/frontend/src/pages/signOut.tsx
- packages/frontend/src/pages/signUp.tsx
- packages/frontend/src/routes.tsx
- packages/frontend/src/utilities.ts
I had to do this because I needed it for the full-test:
- Moved all routes to a different file `routes.tsx`.  If any one has confict with the currect changes, please do contact me.
- Refactored how `AuthContext` is implemented.  It is now available everywhere in the app and is working properly.  If any one needs access to authentication info please do reach out.
> Refactor `AuthContext` and routes

- packages/frontend/src/pages/signIn.tsx
- packages/frontend/src/pages/signUp.tsx
modified css and added the show and hide password icon
> Modify signin and signup UI

- packages/frontend/src/components/Button.tsx
- packages/frontend/src/components/Modal.tsx
- packages/frontend/src/pages/ListeningQuestionsPage.tsx
- packages/frontend/src/pages/ReadingQuestionsPage.tsx
- packages/frontend/src/pages/SpeakingCardPage.tsx
- packages/frontend/src/pages/TestPage.tsx
For now:
- I've adapted a pop-up modal dialog I've found online
- Added a utility button component
Both are open to suggestions in what they look like and in how they're implemented.  Remaining work is to polish the modal and use it to provide help material, for each test.
> Instructions

- packages/frontend/src/components/Nav.tsx
- packages/frontend/src/pages/SpeakingCardPage.tsx
I forgot to push these before :)
- Increase menu width on mobile
- Remove fixed card height from `SpeakingCardPage.tsx`
> Minor UI changes

- packages/frontend/src/components/FButton.tsx
- packages/frontend/src/components/resumeCard.tsx
- packages/frontend/src/sections/continuePast.tsx
- added shadows to cards
- removed animamtion
- fixed padding
- fixed button size on mobile
> home UI changes

- packages/frontend/src/components/carousel.tsx
There was a problem with the width of the carousel and it has been done
> Editing the width of the carousel

- packages/frontend/src/components/CountdownTimer.tsx
- packages/frontend/src/components/Spinner.css
- packages/frontend/src/components/Spinner.tsx
- packages/frontend/src/components/examsHeader.tsx
- packages/frontend/src/pages/FullTestPage.tsx
- packages/frontend/src/pages/ReadingQuestionsPage.tsx
- packages/frontend/src/pages/TestPage.tsx
Added some goodies.
- Improved countdown timer.  I'm now running `onTimeUp` on 1 second.  The issue with the old implementation is that the clear interval was not clearing.
- Added a loading spinner :)
> Fulltest Continued

- package-lock.json
- package.json
- packages/frontend/src/pages/signIn.tsx
- packages/frontend/src/pages/signUp.tsx
- added "toast" messages to both signin and signup pages
- navigate to home page after successful signin/signup after the toast message is closed
- package was updated to include react-toastify
> Toast Message and Navigate to Home

- packages/frontend/src/pages/ListeningQuestionsPage.tsx
> Use listening urls from database

- packages/frontend/src/components/IntermediatePage.tsx
- packages/frontend/src/pages/FullTestPage.tsx
I added this so someone can start working on designing this component.
Note that when the timer is up I get the error
```
Warning: Cannot update a component (`FullTestPage`) while rendering a different component (`CountdownTimer`). To locate the bad setState() call inside `CountdownTimer`, follow the stack trace as described in 
...
```
I don't care!
> Extract a new component - `IntermediatePage` + Add toasts

- packages/frontend/src/components/ConfirmFullTestStart.tsx
- packages/frontend/src/components/TestComponents.tsx
- packages/frontend/src/pages/LAnswersPage.tsx
- packages/frontend/src/pages/ListeningQuestionsPage.tsx
- packages/frontend/src/pages/RAnswersPage.tsx
- packages/frontend/src/pages/ReadingQuestionsPage.tsx
- packages/frontend/src/pages/WritingPage.tsx
- Started working on `ConfirmFullTestStart` page, @saraisa12.
- Minor improvements for mobile experience.
> Design changes

- packages/functions/src/postConfirmation.ts
a new record will be added for the student plan when they sign up.
> adding a new record for the student plan

- packages/frontend/src/components/ProgressBar.tsx
- packages/frontend/src/pages/PlacementTest.tsx
idk how to modify  the final result page
> Modify UI placment

- packages/frontend/src/Layout.tsx
- packages/frontend/src/components/Button.tsx
- packages/frontend/src/components/TestComponents.tsx
- packages/frontend/src/pages/DevPage.tsx
- packages/frontend/src/pages/LAnswersPage.tsx
- packages/frontend/src/pages/RAnswersPage.tsx
- packages/frontend/src/pages/sections.tsx
- packages/frontend/src/routes.tsx
- Added navigation to `Button`
- Minor changes for mobile experience
> Add dev page + other changes

- packages/frontend/src/components/CountdownTimer.tsx
This was a question in an interview test.  Thought I'd contribute it here.
> Proper clearing of interval in `CountdownTimer`

- packages/frontend/src/AuthContext.tsx
- packages/frontend/src/pages/signIn.tsx
- packages/frontend/src/pages/signUp.tsx
- packages/frontend/src/routes.tsx
- packages/frontend/src/utilities/authUtilities.tsx
- Redirect when user tries to access a page that requires he signs in
- Redirect user after he signes in
> Add authentication in routes

- packages/frontend/src/AuthContext.tsx
- packages/frontend/src/Layout.tsx
- packages/frontend/src/components/Nav.tsx
- Use `AuthContext` in the navbar
- Update `AuthContext` every 5 minutes
Someone please make sure this works as it should, and make sure the nav bar is update when you sign in, sign out, etc.
> Fix navbar delay

- packages/frontend/src/AuthContext.tsx
- packages/frontend/src/components/Nav.tsx
- packages/frontend/src/pages/signIn.tsx
- packages/frontend/src/pages/signUp.tsx
- packages/frontend/src/utilities/authUtilities.tsx
- Fix issue of redirect, when user info is not loaded yet
> Authentication fixes
